'use strict';

const {parseArgs} = require('../utils/parse');

function handleInit({command, args, universe}) {
  // Initialize the PluginResponse structure
  let pluginResponse = {
    apiVersion: "v1alpha1",
    command,
    universe,
  };

  // } else if (command === 'flags') {
  //   // Add flags to the response
  //   pluginResponse.flags.push({
  //     Name: "domain",
  //     Type: "string",
  //     Default: "example.domain.com",
  //     Usage: "sets the domain added in the scaffolded initFile"
  //   });
  // } else {
  // parse the flags
  // TODO: error handling
  const parsedArgs = parseArgs(args);

  let domain;
  if (parsedArgs === null) domain = "example.domain.com"
  else domain = parsedArgs["domain"]

  pluginResponse.universe = {
    ...universe,
    "initFile": `This is the file generated by init command, with domain: ${domain}`
  };

  return pluginResponse;
}


module.exports = {handleInit}
