'use strict';

const {parseArgs} = require('../utils/parse');

function handleInit({command, args, universe}) {
  let {domain} = parseArgs(args);

  if (!domain) domain = "example.domain.com"

  universe["initFile"] = `This is the file generated by init command, with domain: ${domain}`;

  return {
    apiVersion: "v1alpha1",
    command,
    universe,
  };
}


module.exports = {handleInit}
