'use strict';
const {parseArgs, formatFlags} = require('../utils/parse');

function handleInit({apiVersion, command, args}) {
  // get the flags
  // const formatArgs = JSON.stringify(args, null, 2)

  // parse the flags
  const parsedArgs = parseArgs(args);

  return {
    apiVersion,
    command,
    metadata: {
      Description: "The `init` subcommand of the sample js plugin is meant to initialize a project via Kubebuilder. It scaffolds a single file: `initFile`",
      Examples: `Scaffold with the defaults:\n$ kubebuilder init --plugins=kb-js-plugin/v1`
    },
    universe: {
      "initFile": `This is the file generated by init command, with flags:\n${formatFlags(parsedArgs)}`
    }
  }
}

module.exports = {handleInit}
